### ISSUE TITLE
illegal memory access was encountered while running default GPT2 - small Training on NVIDIA GPU

### ISSUE THREAD

**Issue by kannan-scalers-ai** [karpathy/nanoGPT#192]
I am trying to train the gpt2-small model with DDP on a  8x80GB H100 Nvidia GPUs. 

Irrespective of the pytorch nightly versions, I always ends up with the below error while starting the training.

```python
Traceback (most recent call last):
  File "/mnt/code/nanoGPT/train.py", line 297, in <module>
    scaler.scale(loss).backward()
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/autograd/__init__.py", line 199, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/autograd/function.py", line 275, in apply
    return user_fn(self, *args)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1906, in backward
    out = call_compiled_backward()
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1882, in call_compiled_backward
    out = call_func_with_args(
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1021, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 224, in run
    return model(new_inputs)
  File "/tmp/torchinductor_root/u3/cu3tp6cjigxwuvzvyneu7ntad6tktw4odqgkm6mop4eggl5ghfuj.py", line 473, in call
    triton__4.run(buf14, buf15, 262144, grid=grid(262144), stream=stream4)
  File "/root/miniconda3/envs/train/lib/python3.10/site-packages/torch/_inductor/triton_ops/autotune.py", line 188, in run
    result = launcher(
  File "<string>", line 6, in launcher
RuntimeError: Triton Error [CUDA]: an illegal memory access was encountered
```

Below are the versions of the packages I am using

  CUDA: `11.8`
  Nvidia Driver: `520.61.05`
  Torch: `2.0.0.dev20230210+cu118`
  Torch-Triton: `2.0.0`

The training works with a single GPU without using the `torchrun` for the `train_shakespeare_char.py`.  Training the  shakespeare using the `torchrun` command freezes after logging the step 0.

I have tried the following options to try fix the above issue
1. Different versions of torch nightly packages from: [https://download.pytorch.org/whl/nightly/torch/](https://download.pytorch.org/whl/nightly/torch/)
2. CUDA versions 11.7 with nvidia driver version 515
3. Varying batch size for the model training.
4. Training using other similar datasets.

**Comment by stanleyshly** [comment]
I'm getting a similar error on ROCm; I filled an issue on the [pytorch repo](https://github.com/pytorch/pytorch/issues/97074).

**Comment by hypnopump** [comment]
any news?

**Comment by kannan-scalers-ai** [comment]
It turned out to be an issue with the 8th H100 GPU on the machine. Once we swapped out that for a new one, the issue got resolved.

**Comment by hypnopump** [comment]
Well i'm having a similar issue. And i'm not sure it's a GPU error, as changing the number of heads and hiddem dim fixes it.
