### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by Keller2** [karpathy/nanoGPT#281]
Whenever trying to run train.py from the repository I run into the issue "AssertionError: Torch not compiled with CUDA enabled" does anyone have any advice on how to fix this?

**Comment by bhaveshbheda** [comment]
plz change this value in train.py 
device = 'cpu'
at line no 72 or nearby

**Comment by Keller2** [comment]
> plz change this value in train.py device = 'cpu' at line no 72 or nearby

That fixed it thanks
